name = input("enter the name")

print("your name is " + name)
age = input("enter the age")
age = int(age)
year = str((2019 - age)+100)
print(name +"will be 100 years old in the year "+ year)
print (year)
print(age)
print(year)